---
repos:
  - repo: https://github.com/ambv/black
    rev: 21.5b2
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/pylint
    rev: v2.8.3
    hooks:
      - id: pylint
